# Generated by Django 3.0.3 on 2020-04-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_lastupdatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet',
            new_name='tweet_id',
        ),
    ]
